import "../components/header.js";
import "../components/sidebar.js";
import "../components/bucket.js";
import "../components/add_button.js";
import "../components/ingredients_list.js";
import "../components/mixer.js"
import "./dragable.js"
import "./hall.js"
import "./color.js"
import "./scripts.js";
